;this file for FamiTone4 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


TestMusic3_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Caribou
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Pause

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
@env4:
	.byte $c2,$06,$c1,$00,$02


; Caribou
@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	.byte $80,$20,$85,$84,$1b,$80,$1c,$83,$19,$91,$19,$81,$1c,$81,$1e,$81
	.byte $1f,$87,$1e,$83
@ref1:
	.byte $20,$85,$84,$1b,$80,$1c,$83,$19,$91,$1c,$81,$1c,$81,$1c,$81,$1b
	.byte $1b,$83,$1b,$85
@ref2:
	.byte $20,$85,$84,$1b,$80,$1c,$83,$19,$91,$19,$81,$1c,$81,$1e,$81,$1f
	.byte $87,$1e,$83
@ref3:
	.byte $81,$1c,$1c,$81,$1c,$81,$1c,$81,$1b,$85,$1b,$81,$17,$81,$1e,$1e
	.byte $81,$1e,$81,$1e,$81,$1c,$83,$1b,$81,$17,$81,$1b,$81
@ref4:
	.byte $1c,$81,$00,$85,$1b,$81,$1c,$81,$00,$85,$1b,$81,$1c,$81,$00,$85
	.byte $1b,$81,$1c,$85,$1e,$85
@ref5:
	.byte $1c,$81,$00,$85,$1b,$81,$1c,$81,$00,$85,$1b,$81,$1c,$81,$00,$85
	.byte $1b,$81,$1c,$81,$17,$81,$17,$81,$82,$17,$81
	.byte $ff,$11
	.word @ref0
	.byte $ff,$12
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$1d
	.word @ref3
	.byte $ff,$16
	.word @ref4
	.byte $ff,$1a
	.word @ref5
	.byte $fd
	.word @song0ch0loop

; Caribou
@song0ch1:
@song0ch1loop:
@ref12:
	.byte $82,$00,$85,$82,$0d,$85,$00,$85,$0d,$81,$00,$89,$0d,$85,$10,$81
	.byte $00,$81,$12,$81,$00,$81
@ref13:
	.byte $00,$85,$0d,$85,$00,$85,$0d,$81,$00,$89,$0d,$85,$10,$81,$00,$81
	.byte $12,$81,$00,$81
	.byte $ff,$14
	.word @ref13
	.byte $ff,$14
	.word @ref13
	.byte $ff,$14
	.word @ref13
	.byte $ff,$14
	.word @ref13
@ref18:
	.byte $81,$84,$2c,$87,$28,$83,$2c,$87,$28,$83,$2c,$87,$28,$83,$2a,$87
	.byte $2a,$81
@ref19:
	.byte $81,$2c,$87,$28,$83,$2c,$87,$28,$83,$2c,$87,$28,$85,$27,$81,$27
	.byte $85
@ref20:
	.byte $81,$2c,$87,$28,$83,$2c,$87,$28,$83,$2c,$87,$28,$83,$2a,$87,$2a
	.byte $81
@ref21:
	.byte $81,$2c,$2c,$81,$2c,$81,$2c,$81,$2a,$85,$2a,$81,$27,$81,$2a,$2a
	.byte $81,$2a,$81,$2a,$81,$27,$83,$27,$81,$23,$85
@ref22:
	.byte $00,$85,$82,$0d,$85,$00,$85,$0d,$81,$00,$89,$0d,$85,$10,$81,$00
	.byte $81,$12,$81,$00,$81
	.byte $ff,$14
	.word @ref13
	.byte $fd
	.word @song0ch1loop

; Caribou
@song0ch2:
@song0ch2loop:
@ref24:
	.byte $80,$28,$81,$20,$81,$00,$81,$20,$81,$28,$81,$20,$81,$00,$81,$20
	.byte $81,$28,$81,$20,$81,$00,$81,$20,$81,$28,$81,$20,$81,$00,$81,$20
	.byte $81
@ref25:
	.byte $28,$81,$20,$81,$00,$81,$20,$81,$28,$81,$20,$81,$00,$81,$20,$81
	.byte $28,$81,$20,$81,$00,$81,$20,$81,$28,$81,$20,$81,$00,$81,$20,$81
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $ff,$20
	.word @ref25
	.byte $fd
	.word @song0ch2loop

; Caribou
@song0ch3:
@song0ch3loop:
@ref36:
	.byte $84,$09,$81,$09,$81,$00,$82,$0b,$86,$0d,$81,$84,$09,$81,$09,$81
	.byte $00,$82,$0b,$86,$0d,$81,$84,$09,$81,$09,$81,$00,$82,$0b,$86,$0d
	.byte $81,$84,$09,$81,$09,$81,$00,$82,$0b,$86,$0d,$81
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $ff,$20
	.word @ref36
	.byte $fd
	.word @song0ch3loop

; Caribou
@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; Pause
@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref60:
	.byte $bf
	.byte $fd
	.word @song1ch0loop

; Pause
@song1ch1:
@song1ch1loop:
@ref61:
	.byte $bf
	.byte $fd
	.word @song1ch1loop

; Pause
@song1ch2:
@song1ch2loop:
@ref62:
	.byte $82,$1c,$81,$00,$89,$1c,$81,$00,$89,$1c,$81,$00,$89,$19,$81,$00
	.byte $81,$19,$85
	.byte $fd
	.word @song1ch2loop

; Pause
@song1ch3:
@song1ch3loop:
@ref63:
	.byte $84,$0b,$00,$83,$0b,$00,$83,$0b,$00,$83,$09,$00,$83,$0b,$00,$83
	.byte $0b,$00,$83,$0b,$00,$83,$09,$00,$83
	.byte $fd
	.word @song1ch3loop

; Pause
@song1ch4:
@song1ch4loop:
@ref64:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
